### ISSUE TITLE
showCalendarDisplay

### ISSUE THREAD

**Issue by akstudio** [mikecoj/MCDatepicker#22]
I am unsure if this is working properly, as I cannot get it to work.

Example:
`const secondCalendar = MCDatepicker.create({ el: '#end_date', showCalendarDisplay: 'false'});`

I need the ability for the user to manually add in a date into the input field, with an option to launch the calendar via a separate button.

I have all of it almost working, I just need to NOT have the calendar launched when the input field is in focus (clicked) - but rather, launch the calendar from a button, and then populate the form field when clicking on OK.

**Comment by louis123562** [comment]
Hey,

you do not need to specify an element when creating the calender object.

You can open up the calender with the [open() function](https://mcdatepicker.netlify.app/docs/methods#open). You can call it in an on-click event of the button.

But you will have to use the [onClose()](https://mcdatepicker.netlify.app/docs/event-hooks#onclose) event hook in order to get the selected date and fill the value of your (date)- input.

This is just a workaround - maybe it fits your needs.

**Comment by louis123562** [comment]
Here is an example of my "workaround": https://jsfiddle.net/louis123562/k53gm7r1/1/

One of the advantages of using the event-hooks is, that you can also react to reset- and cancel events.

**Comment by mikecoj** [comment]
Hi there,
the value of the `showCalendarDisplay` option should be the type of `boolean` not `string`. Just fixed that in the docs.

hey, @louis123562, thanks for your help!

Here is an example using `onSelect()` hook: https://jsfiddle.net/mike_cojocari/0my2eo5d/19/
